---
  - name: Check if ShoperHO App exists
    stat: path="{{ shoper_path }}/apps/shoperho"
    register: app

  - name: Get the ShoperHO app
    command: shoper get-app shoperho {{ shoperho_repo_url }} --branch {{ shoperho_branch }}
    args:
      creates: "{{ shoper_path }}/apps/shoperho"
      chdir: "{{ shoper_path }}"
    when: not app.stat.exists and not without_shoperho

  - name: Check whether the site already exists
    stat: path="{{ shoper_path }}/sites/{{ site }}"
    register: site_folder
    when: not without_site

  - name: Create a new site
    command: "shoper new-site {{ site }} --admin-password '{{ admin_password }}' --mariadb-root-password '{{ mysql_root_password }}'"
    args:
      chdir: "{{ shoper_path }}"
    when: not without_site and not site_folder.stat.exists

  - name: Install ShoperHO to default site
    command: "shoper --site {{ site }} install-app shoperho"
    args:
      chdir: "{{ shoper_path }}"
    when: not without_site and not without_shoperho
...