---
- name: Install deps
  yum:
    name:
      - policycoreutils-python
      - selinux-policy-devel
    state: present
  when: ansible_distribution == 'CentOS'

- name: Check enabled SELinux modules
  shell: semanage module -l
  register: enabled_modules
  when: ansible_distribution == 'CentOS'

- name: Copy shprho_selinux policy
  copy: src=shprho_selinux.te dest=/root/shprho_selinux.te
  register: dest_shprho_selinux_te
  when: ansible_distribution == 'CentOS'

- name: Compile shprho_selinux policy
  shell: "make -f /usr/share/selinux/devel/Makefile shprho_selinux.pp && semodule -i shprho_selinux.pp"
  args:
    chdir: /root/
  when: "ansible_distribution == 'CentOS' and enabled_modules.stdout.find('shprho_selinux') == -1 or dest_shprho_selinux_te.changed"
...